def getConfigFromGitea(branch, credentials, project_folder) {
    sh "rm -r -f " + project_folder
    withCredentials([string(credentialsId: credentials, variable: 'gitea_token')]) {
        sh "git clone -c http.sslVerify=false -b " + "develop" + " https://" + gitea_token + ":x-oauth-basic@gitea.gpapdev.cnag.eu/gitea/ejodry/" + project_folder
        sh "cd " + project_folder + " && git fetch --all"

        try {
            sh "cd " + project_folder + " && git checkout -b " + branch
        }
        catch(Exception e) {
            sh "cd " + project_folder + " && git checkout  " + branch
            println(e);
        }

        try {
            sh "cd " + project_folder + " && git pull origin " + branch
        }
        catch(Exception e) {
            println(e);
        }

        // Remove config.ts file
        sh "rm -f ./client/src/lib/config.ts"
        // Replace by the one stored in gitea
        sh "cp -r " + project_folder + "/config.ts ./client/src/lib/config.ts"
    }
}

def BuildAndCopyMibsHere(branch, credentials, project_folder, content) {
    sh "rm -r -f " + project_folder
    withCredentials([string(credentialsId: credentials, variable: 'gitea_token')]){
        sh "git clone --depth 1 -c http.sslVerify=false -b " + branch + " https://" + gitea_token + ":x-oauth-basic@gitea.gpapdev.cnag.eu/gitea/ejodry/" + project_folder + " " + project_folder
        sh "cd " + project_folder + " && git fetch --all"
        sh "cd " + project_folder + " && git config pull.rebase false"

        try {
            sh "cd " + project_folder + " && git pull origin " + branch
        } catch (Exception e) {
            println(e)
        }

        // Step 1: Remove all old files
        sh "cd " + project_folder + " && find . -type f \\( -name \'*.js\' -or -name \'*.html\' -or -name \'*.css\' \\) -delete"

        // Step 2: Stage the deletions and commit them
        sh "cd " + project_folder + " && git add -A"

        try {
            sh "cd "+ project_folder + " && git commit -m 'Clean up old files'"
        } catch (Exception e) {
            println("No changes to commit: ${e.getMessage()}")
        } 

        // Step 3: Copy new content (if any) and commit the new files
        if (content != null) {
            sh "cp -r " + content + " " + project_folder + "/."

            // Check for any new changes and commit them
            sh "cd " + project_folder + " && if [ \$(git status --porcelain | wc -l) -gt 0 ]; then git add -A && git commit -m 'Latest build' && git push -f origin " + branch + "; else echo 'No changes to commit'; fi"
        }
    }
}


pipeline {
    agent {
        any { image 'node:23-alpine' }
    }
    stages {
        stage('npm install') {
            steps {
                dir('./client'){
                    sh 'rm -rf ./node_modules/*'
                    sh 'npm install'
                }
            }
        }
        stage('inject config') {
            steps {
                getConfigFromGitea("master", "gitea_apapakon_token", "omicsdm-v2_client_config")
            }
        }
        stage('npm build') {
            steps {
                dir('./client'){
                    // TODO: add fetch client generation when server will be online 
                    sh 'rm -rf ./build/*'
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'client/build/*', fingerprint: true
            sh 'rm -rf ./client/node_modules'
        }
        success {
            BuildAndCopyMibsHere(env.BRANCH_NAME, 'gitea_apapakon_token','omicsdm-v2_client_artifact','client/build/*')
        }
    }
}
