-- psql -U devel_omicsdm2_3tr_rw devel_omicsdm2_3tr_testprod

DELETE FROM "ASSO_DATASET_FILE";
DELETE FROM "ASSO_DATASET_TAG";
DELETE FROM "ASSO_LIST_GROUP";
DELETE FROM "ASSO_PERM_DATASET_FILES";
DELETE FROM "ASSO_PERM_DATASET_SELF";
DELETE FROM "ASSO_PERM_PROJECT_DATASETS";
DELETE FROM "ASSO_USER_GROUP";
DELETE FROM "DATASET";
DELETE FROM "FILE";
DELETE FROM "GROUP";
DELETE FROM "HISTORY";
DELETE FROM "LISTGROUP";
DELETE FROM "PROJECT";
DELETE FROM "TAG";
DELETE FROM "UPLOAD";
DELETE FROM "UPLOADPART";
DELETE FROM "USER";
DELETE FROM "VISUALIZATION";

SELECT setval('"DATASET_id_seq"', 1, true);
SELECT setval('"FILE_id_seq"', 1, true);
SELECT setval('"LISTGROUP_id_seq"', 1, true);
SELECT setval('"PROJECT_id_seq"', 1, true);
SELECT setval('"UPLOAD_id_seq"', 1, true);
SELECT setval('"VISUALIZATION_id_seq"', 1, true);
