services:
  api-db:
    image: postgres:16-bookworm
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=biodm
    healthcheck:
      test: pg_isready -U postgres
    stdin_open: true
    tty: true
    networks:
      biodm-dev:
        ipv4_address: 10.10.0.2

  kc-db:
    image: postgres:16-bookworm
    container_name: kc-db
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres
    networks:
      biodm-dev:
        ipv4_address: 10.10.0.5

  keycloak:
    build:
      context: ./docker/
      dockerfile: Dockerfile.keycloak-22.0_local-certs
      args:
        - _KC_DB=postgres
        - _KC_DB_USERNAME=postgres
        - _KC_DB_PASSWORD=pass
        - _KC_HOSTNAME=keycloak.local
        - _KC_DB_URL=jdbc:postgresql://10.10.0.5:5432/keycloak
    container_name: keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=10.10.0.5:5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=1234
      - KEYCLOAK_HOSTNAME_DEBUG=true
      - KEYCLOAK_HOSTNAME_STRICT=false
      - KEYCLOAK_HTTP_ENABLED=true
      - KEYCLOAK_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
    command: [
      "start-dev",
      "--import-realm",
      "--hostname-strict", "false",
    ]
    depends_on:
      - kc-db
    links:
      - kc-db
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    healthcheck:
      test: /health.sh
      interval: 5s
      timeout: 5s
      retries: 10
    hostname: keycloak.local
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      biodm-dev:
        ipv4_address: 10.10.0.3

  s3bucket:
    image: bitnami/minio:2024-debian-12
    ports:
      - 9000:9000
      - 9001:9001
    tty: True
    healthcheck:
      test: |
        curl -Is http://s3bucket:9000/minio/health/live | head -n 1 | grep 200
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=bucketdevel3tropal
    restart: unless-stopped
    networks:
      biodm-dev:
        ipv4_address: 10.10.0.4

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    ports:
      - 9080:8080
    environment:
      API_URL: http://localhost:8000/schema

networks:
  biodm-dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
